name: Dependency checker

on:
  push:
    branches:
      - main
      # release branches have the form v1.9.x
      - 'v[0-9].*[0-9].x'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "**.py"
      - "pyproject.toml"
      - "!.github/**/*.py"
      - "!rest_api/**/*.py"
      - "!test/*"

env:
  PYTHON_VERSION: "3.8"

jobs:

  base-install:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Haystack with no extras
      run: |
        pip install git+https://github.com/ZanSara/generalimport.git@handling-classes
        pip install pydantic tenacity
        pip install --no-deps .

    - name: Try to import
      run: python -c 'import haystack'
